name: Auto.Tag

on:
  push:
    tags-ignore:
      - '**'
    branches:
      - '**'

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: phish108/autotag-action@v1.1.64
      with:
        github-token: ${{ secrets.GH_PAT }}
        with-v: "true"
        release-branch: "main"
